### ISSUE TITLE
Roadmap to version 2.0

### ISSUE THREAD

**Issue by andrasfuchs** [freerouting/freerouting#326]
There are [a few issues already assigned to the 2.0 milestone](https://github.com/freerouting/freerouting/issues?q=is%3Aissue+milestone%3A2.0+) and there are a few steps that I plan to complete before the next release.

I copy them here from my personal notes for transparency, but I can't give deadlines since I have very little time to work on Freerouting nowadays. As always, any help is welcome!

- [x] improve the GUI
  - [x] fix a few English typos
  - [x] add clarification tooltips
  - [x] merge the advanced router settings into router settings window
  - [x] ~~add UI binding between the settings class and their UI control counterparts (with validation)~~
  - [x] ~~change fanout, autorouter and optimizer checkboxes to dropdowns/radiobuttons to select the algorithm to be used~~
  - [x] ~~change the via allowance checkbox to allowed via types dropdown (see [#305](https://github.com/freerouting/freerouting/issues/305#issuecomment-2253357271))~~
  - [x] ~~make rule values that were read from the input file read only~~
  - [x] add tutorial steps if no file is opened at the moment (and include a few test files to play with)
- [x] add RESTful web API (using [Jetty](https://jetty.org/)+[Jersey](https://eclipse-ee4j.github.io/jersey/)) + generate OpenAPI documentation (using [Swagger.io](https://swagger.io/tools/open-source/open-source-integrations/))
  - [x] create a advanced configuration manager that handles command line arguments and environment variables
  - [x] add support for Stream inputs and outputs (instead of supporting only File inputs/outputs)
  - [x] separate all the parameters into a class that the routing algorithm needs to complete a job
  - [x] make BatchFanout and BatchAutorouter support headless mode (without using GuiBoardManager)
        (note: the optimizer, BatchOptRoute isn't supported yet)
  - [x] modify the method signatures in the backend to expect this new settings class
  - [x] add endpoints to create and run jobs, upload input files, settings and query jobs while they are running, and download results
  - [x] ~~add documentation attributes to all public classes and methods~~
  - [x] ~~generate OpenAPI documentation based on those attributes~~
  - [x] add versioning to the API, including a "dev" version where mocked data is returned
  - [x] ~~add authentication to the public non-dev versions to request the enviroment.host and profile.email data points~~
  - [x] add a new session manager that would standardize the job creation, running and monitoring for both the GUI and API
  - [x] temporarily save input and output files that were processed through the API to help debugging
  - [x] ~~replace the GUI-bound messages with a job-specific message queue~~
  - [x] add Session ID and Job ID as [_topics_](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#topics-and-subscriptions) to store these accordingly in their own message store
  - [x] show a basic API information page if the user call a non-existant API endpoint
  - [x] give back meaningful error messages to the API calls
  - [x] remove input/output data from API analytics
  - [x] add clearance violations to statistics
  - [x] fix the issue with API SES output
- [x] telemetry
  - [x] request for an email address after a successful routing if the user completed at least 5 jobs
  - [x] add profile editing form to the GUI
  - [x] add option to opt out of telemetry
  - [x] add logging and telemetry to the API
  - [x] ~~mirror some basic telemetry reporting to a protected API endpoint~~
  - [x] ~~send e-mail confirmation request e-mails to participants (and give them free API credits for it)~~
- [x] add an option to disable both the GUI and the API and act as a CLI command line utility (headless mode)
- [x] add a few JUnit test + GitHub actions to execute them on each build
  - [x] add an option to generate board stats after a completed routing job
  - [x] add JUnit test cases with some sample DSN files to verify if the stats are correct
  - [x] integrate JUnit test runs into the GitHub workflow
- [x] add Docker support
  - [x] create a docker image manually
  - [x] run the container locally
  - [x] run the on Azure
  - [x] ~~create a GitHub action to do the build automatically for each new release~~
  - [x] add mounted storage support to save configuration and other temporary files
- [x] update MVN Repository manually ~~+ GitHub actions to do it automatically for the next release~~
- [x] update KiCad plugin
  - [x] add macOS Homebrew support
  - [x] handle paths that contan spaces and/or Unicode characters
  - [x] change the temporary file location from the current directory to `%temp%/freerouting/`
  - [x] remove the not-used Markdown files from the plugin archive
  - [x] update references to v2.0
  - [x] add logging support for the plugin as well
  - [x] check and remove older JRE installations in the %temp% folder
- [x] publish API to https://api.freerouting.app using [Azure API Management](https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts)
  - [x] push the Docker image to Azure Docker Registry
  - [x] run the container on Azure
  - [x] run the container on Raspberry Pi
  - [x] expose the API at http://api.freerouting.app
  - [x] ~~set up authentication and give access rights to a small closed beta group to gather feedback~~
  - [x] ~~set up rate limiting (to prevent excessive costs)~~
- [x] documentation - settings in freerouting.json file
  - [x] add general information about the file and its default location
  - [x] describe the valid new `--` command line arguments
  - [x] describe the usage of environment variables to change settings
  - [x] describe even the "under the hood" parameters so that users can hack them as much as they like
- [x] documentation - RESTful API usage, samples, OpenAPI access
- [x] ~~documentation - [EasyEDA](https://easyeda.com/) and [tscircuit](https://tscircuit.com/) integration~~
- [x] documentation - v2.0 release draft: new features, Java 21, localized texts+translations, GUI, API, freerouting.json, sponsors
- [x] documentation - new screenshots, update README, stats for 2024Q1, 2024Q2 and 2024Q3

**Comment by seveibar** [comment]
Very excited for tscircuit + freerouting. A lot more people will be able to build electronics if we reduce/eliminate the need to autoroute for simple boards!!!

**Comment by dpalic** [comment]
Hi @andrasfuchs 
I may help you with rest/openapi, docker, junit and mvn
but it would require to get some kickstart from your end.
Is it possible to organize a zoom call with all potential helpers?

**Comment by andrasfuchs** [comment]
@dpalic That would be awesome, thank you for considering. 
Please feel free to schedule a convenient time using this link: https://cal.com/fuchs

**Comment by andrasfuchs** [comment]
@imrishabh18 It is already possible, but many things are still moving around, so please wait at least a few weeks until I can get to a version that works as intended and I got some testing and documentation done.

I will need to focus on my other responsibilities in the next few days and probably next week, so I can't promise any deadlines, but if you have the capacity to implement the OpenAPI or any other tasks from the above list, that would be great and I would check your PRs as soon as I can.

**Comment by Ashleycodesseo** [comment]
hi @andrasfuchs I saw that you need help documenting for the RESTful API portion of this project. I'm looking to get some practice and experience documenting so please add me on and let me know what you need help with. I'd be happy to contribute. Thanks

**Comment by andrasfuchs** [comment]
@Ashleycodesseo Fantastic, thank you! 
Please drop me a line to info@freerouting.app with your preferred e-mail address, so that I can add you to Postman workspace where you can see the endpoints we have. There is a documentation section in Postman as well, but I haven't used it yet. I plan to put the documentation both on GitHub and into the code using Java attributes that will be used by the OpenAPI interface.
All suggestions are welcome, the current version of the API is just a preview, so don't hesitate to recommend changes to the endpoints and their parameters.

**Comment by Ashleycodesseo** [comment]
@andrasfuchs you got it! I'm working through my projects today and I will message you once you email me and I get started on this. My email is ashleycodesseo@gmail.com Thank you!

**Comment by andrasfuchs** [comment]
@imrishabh18 @Ashleycodesseo 
I have just published the API to https://api.freerouting.app and I created environments accordingly in Postman.

![image](https://github.com/user-attachments/assets/51931d79-5941-42c4-a746-fc615e458612)

You can change your current testing environment in the top right corner in Postman. `Localhost` can be used when you have Freerouting API running locally, `beta` is for my testing environment, and `production` set the API URL to _api.freerouting.app_.

Feel free to play with them, don't worry, you can't break anything, or if you do, that's a valuable feedback too :) It will be changed in the following days and weeks, and there will be a required authentication for the production access as well.

Let me know if you have any issues, questions or other feedback.

**Comment by Ashleycodesseo** [comment]
ok @andrasfuchs I will take a look at it today

**Comment by andrasfuchs** [comment]
@Ashleycodesseo I've just created a very basic API documentation here: [API_v1.md](https://github.com/freerouting/freerouting/blob/master/docs/API_v1.md). I hope it helps, and I would be greatful if you could improve it. ;)
